In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression


In [2]:
import pandas as pd

df = pd.read_csv("dataset/clean_sql_dataset.csv")

print(df.columns.tolist())

['Query', 'Label']


In [3]:
print(df["Label"].value_counts())
print(df["Label"].value_counts(normalize=True))

Label
1    77750
0    70576
Name: count, dtype: int64
Label
1    0.524183
0    0.475817
Name: proportion, dtype: float64


In [4]:
X = df["Query"]
y = df["Label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nTraining distribution:")
print(y_train.value_counts(normalize=True))

print("\nTesting distribution:")
print(y_test.value_counts(normalize=True))

Training samples: 118660
Testing samples: 29666

Training distribution:
Label
1    0.524187
0    0.475813
Name: proportion, dtype: float64

Testing distribution:
Label
1    0.524169
0    0.475831
Name: proportion, dtype: float64


In [5]:
vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2,
    max_features=100000
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Training shape:", X_train_tfidf.shape)
print("Testing shape:", X_test_tfidf.shape)

Training shape: (118660, 100000)
Testing shape: (29666, 100000)


In [6]:
print(X_train_tfidf.shape)
print(vectorizer.get_feature_names_out()[:50])


(118660, 100000)
['\t"' "\t'" '\t(' '\t(s' '\t(se' '\t(sel' '\t)' '\t0' '\t0x' '\t=' '\ta'
 '\tan' '\tand' '\tas' '\tf' '\tl' '\to' '\tor' '\ts' '\tt' '\tw' '\twh'
 '\twhe' '\twher' '\n"' "\n'" '\n(' '\n(s' '\n(se' '\n(sel' '\n)' '\n*'
 '\n/' '\n0' '\n0x' '\n=' '\na' '\nan' '\nand' '\nf' '\no' '\nor' '\ns'
 '\nt' '\nw' '\x0b(' '\x0b(s' '\x0b(se' '\x0b(sel' '\x0b)']


In [7]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train_tfidf, y_train)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

In [8]:
y_pred = model.predict(X_test_tfidf)

In [9]:
print(y_pred[:20])
print(y_test.values[:20])

[0 1 0 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0]
[0 1 0 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0]


In [10]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Normal SQL", "SQL Injection"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy : 0.9815950920245399
Precision: 0.9962953162212226
Recall   : 0.9684887459807074
F1 Score : 0.982195265114459

Classification Report:
               precision    recall  f1-score   support

   Normal SQL       0.97      1.00      0.98     14116
SQL Injection       1.00      0.97      0.98     15550

     accuracy                           0.98     29666
    macro avg       0.98      0.98      0.98     29666
 weighted avg       0.98      0.98      0.98     29666


Confusion Matrix:
[[14060    56]
 [  490 15060]]


In [11]:
errors = df.loc[X_test.index][y_test != y_pred]

print(errors[["Query", "Label"]].head(50).to_string(index=False))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Query  Label
                 

In [12]:
import numpy as np

feature_names = vectorizer.get_feature_names_out()
coefficients = model.coef_[0]

top_attack = np.argsort(coefficients)[-30:][::-1]
top_normal = np.argsort(coefficients)[:30]

print("Strongest SQL injection features:")
for i in top_attack:
    print(repr(feature_names[i]), coefficients[i])

print("\nStrongest normal SQL features:")
for i in top_normal:
    print(repr(feature_names[i]), coefficients[i])

Strongest SQL injection features:
'--' 11.522237234454447
' )' 11.040356906130905
' ) ' 10.771715784774544
'/*' 10.54151187421844
'= ' 10.021960530663401
' =' 10.018926770574595
'*/' 9.987083489032909
' = ' 9.909389788883963
') ' 9.637854517082712
"' " 7.514288589871374
'1 ' 6.658242328112102
"1'" 5.926418848403941
') )' 5.841515462883006
' ) )' 5.832660790206406
' ) ) ' 5.795741211238955
') ) ' 5.794800095699729
'( ' 5.678290556752709
' ( ' 5.423243456502296
' 1' 5.291187222768906
'" ' 4.875763925316144
'0x' 4.800677480026264
'0o' 4.620785782747408
' 5' 4.5230681625211435
'l sel' 4.501961894893326
' (' 4.473375108155926
' 9' 4.469345358273241
' 8' 4.458640859283838
' sele' 4.445348336603381
',4' 4.444651965890051
' sel' 4.428868558834144

Strongest normal SQL features:
' ) ;' -4.916465150704976
') ;' -4.495379922941233
'* ) a' -3.0932067016732847
" = '" -3.0630004114885456
"= '" -3.00686013906282
'( s ' -2.719026761594962
' ( s ' -2.719026761594962
'( s )' -2.6752045605848513
's ) f' 

In [13]:
test_queries = [
    # Normal SQL
    "SELECT * FROM users WHERE id = 10",
    "SELECT name, email FROM customers WHERE age > 18",
    "SELECT id FROM products WHERE price < 500",
    "UPDATE users SET name = 'John' WHERE id = 5",
    "DELETE FROM users WHERE id = 100",
    "SELECT COUNT(*) FROM orders",
    "SELECT * FROM employees ORDER BY salary DESC",

    # SQL Injection
    "' OR 1=1 --",
    "' OR '1'='1' --",
    "' UNION SELECT username, password FROM users --",
    "'; DROP TABLE users; --",
    "' OR 1=1 #",
    "admin' --",
    "' AND 1=2 UNION SELECT NULL --",
    "' OR SLEEP(5) --"
]

test_vectors = vectorizer.transform(test_queries)
predictions = model.predict(test_vectors)
probabilities = model.predict_proba(test_vectors)

for query, prediction, probability in zip(
    test_queries,
    predictions,
    probabilities
):
    label = "SQL Injection" if prediction == 1 else "Normal SQL"
    confidence = max(probability) * 100

    print(f"{label:15} | {confidence:6.2f}% | {query}")

SQL Injection   |  94.99% | SELECT * FROM users WHERE id = 10
Normal SQL      |  96.72% | SELECT name, email FROM customers WHERE age > 18
Normal SQL      |  98.18% | SELECT id FROM products WHERE price < 500
SQL Injection   |  94.67% | UPDATE users SET name = 'John' WHERE id = 5
SQL Injection   |  98.11% | DELETE FROM users WHERE id = 100
Normal SQL      |  99.88% | SELECT COUNT(*) FROM orders
Normal SQL      |  99.89% | SELECT * FROM employees ORDER BY salary DESC
SQL Injection   |  99.89% | ' OR 1=1 --
SQL Injection   |  99.93% | ' OR '1'='1' --
SQL Injection   |  97.70% | ' UNION SELECT username, password FROM users --
SQL Injection   |  84.33% | '; DROP TABLE users; --
SQL Injection   |  99.33% | ' OR 1=1 #
SQL Injection   |  92.44% | admin' --
SQL Injection   |  99.87% | ' AND 1=2 UNION SELECT NULL --
SQL Injection   |  99.83% | ' OR SLEEP(5) --


In [14]:
char_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2,
    max_features=100000
)

X_train_char = char_vectorizer.fit_transform(X_train)
X_test_char = char_vectorizer.transform(X_test)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

word_vectorizer = TfidfVectorizer(
    analyzer="word",
    ngram_range=(1, 3),
    min_df=2,
    max_features=50000,
    sublinear_tf=True
)

X_train_word = word_vectorizer.fit_transform(X_train)
X_test_word = word_vectorizer.transform(X_test)

print("Character:", X_train_char.shape)
print("Word:", X_train_word.shape)

Character: (118660, 100000)
Word: (118660, 50000)


In [16]:
from scipy.sparse import hstack

X_train_combined = hstack([
    X_train_char,
    X_train_word
]).tocsr()

X_test_combined = hstack([
    X_test_char,
    X_test_word
]).tocsr()

print("Combined:", X_train_combined.shape)

Combined: (118660, 150000)


In [17]:
from sklearn.linear_model import LogisticRegression

combined_model = LogisticRegression(
    max_iter=1000,
    C=2.0,
    random_state=42
)

combined_model.fit(X_train_combined, y_train)

y_pred_combined = combined_model.predict(X_test_combined)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

print("Accuracy :", accuracy_score(y_test, y_pred_combined))
print("Precision:", precision_score(y_test, y_pred_combined))
print("Recall   :", recall_score(y_test, y_pred_combined))
print("F1 Score :", f1_score(y_test, y_pred_combined))
print(classification_report(
    y_test,
    y_pred_combined,
    target_names=["Normal SQL", "SQL Injection"]
))

print(confusion_matrix(y_test, y_pred_combined))

               precision    recall  f1-score   support

   Normal SQL       0.97      1.00      0.98     14116
SQL Injection       1.00      0.98      0.99     15550

     accuracy                           0.99     29666
    macro avg       0.99      0.99      0.99     29666
 weighted avg       0.99      0.99      0.99     29666

[[14061    55]
 [  375 15175]]


In [19]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(
    n_components=300,
    random_state=42
)

X_train_svd = svd.fit_transform(X_train_combined)
X_test_svd = svd.transform(X_test_combined)

print(X_train_svd.shape)
print(X_test_svd.shape)

(118660, 300)
(29666, 300)


In [20]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.08,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train_svd, y_train)

y_pred_xgb = xgb_model.predict(X_test_svd)

In [21]:
print(classification_report(
    y_test,
    y_pred_xgb,
    target_names=["Normal SQL", "SQL Injection"]
))

print(confusion_matrix(y_test, y_pred_xgb))

               precision    recall  f1-score   support

   Normal SQL       0.98      1.00      0.99     14116
SQL Injection       1.00      0.99      0.99     15550

     accuracy                           0.99     29666
    macro avg       0.99      0.99      0.99     29666
 weighted avg       0.99      0.99      0.99     29666

[[14071    45]
 [  227 15323]]


In [22]:
p_char = model.predict_proba(X_test_tfidf)[:, 1]

p_combined = combined_model.predict_proba(
    X_test_combined
)[:, 1]

p_xgb = xgb_model.predict_proba(
    X_test_svd
)[:, 1]

In [23]:
import numpy as np

ensemble_probability = (
    0.35 * p_char +
    0.35 * p_combined +
    0.30 * p_xgb
)

y_pred_ensemble = (
    ensemble_probability >= 0.5
).astype(int)

In [24]:
print("Accuracy :", accuracy_score(y_test, y_pred_combined))
print("Precision:", precision_score(y_test, y_pred_combined))
print("Recall   :", recall_score(y_test, y_pred_combined))
print("F1 Score :", f1_score(y_test, y_pred_combined))

print(classification_report(
    y_test,
    y_pred_ensemble,
    target_names=["Normal SQL", "SQL Injection"]
))

print(confusion_matrix(y_test, y_pred_ensemble))

               precision    recall  f1-score   support

   Normal SQL       0.98      1.00      0.99     14116
SQL Injection       1.00      0.98      0.99     15550

     accuracy                           0.99     29666
    macro avg       0.99      0.99      0.99     29666
 weighted avg       0.99      0.99      0.99     29666

[[14071    45]
 [  293 15257]]


In [25]:
def detect_sql_injection(query):
    char_features = char_vectorizer.transform([query])
    word_features = word_vectorizer.transform([query])

    combined = hstack([
        char_features,
        word_features
    ]).tocsr()

    reduced = svd.transform(combined)

    p1 = model.predict_proba(char_features)[0, 1]
    p2 = combined_model.predict_proba(combined)[0, 1]
    p3 = xgb_model.predict_proba(reduced)[0, 1]

    probability = (
        0.35 * p1 +
        0.35 * p2 +
        0.30 * p3
    )

    if probability >= 0.5:
        return {
            "prediction": "SQL Injection",
            "probability": probability
        }

    return {
        "prediction": "Safe",
        "probability": 1 - probability
    }

In [26]:
print(detect_sql_injection("' OR 1=1 --"))

{'prediction': 'SQL Injection', 'probability': np.float64(0.9995486106310214)}


In [27]:
print(detect_sql_injection(
    "SELECT name FROM users WHERE id = 10"
))

{'prediction': 'SQL Injection', 'probability': np.float64(0.9955789832420137)}


In [28]:
query = "SELECT name FROM users WHERE id = 10"

char_features = char_vectorizer.transform([query])
word_features = word_vectorizer.transform([query])

combined = hstack([
    char_features,
    word_features
]).tocsr()

reduced = svd.transform(combined)

p_char = model.predict_proba(char_features)[0, 1]
p_combined = combined_model.predict_proba(combined)[0, 1]
p_xgb = xgb_model.predict_proba(reduced)[0, 1]

ensemble = (
    0.35 * p_char +
    0.35 * p_combined +
    0.30 * p_xgb
)

print("Character LR :", p_char)
print("Combined LR  :", p_combined)
print("XGBoost      :", p_xgb)
print("Ensemble     :", ensemble)

Character LR : 0.992475743985586
Combined LR  : 0.9967016613226681
XGBoost      : 0.9978896
Ensemble     : 0.9955789832420137


In [29]:
import re
import numpy as np
import pandas as pd


def extract_sql_features(query):
    q = query.lower()

    features = {
        # Basic properties
        "length": len(query),
        "word_count": len(query.split()),

        # Special characters
        "single_quotes": query.count("'"),
        "double_quotes": query.count('"'),
        "backticks": query.count("`"),
        "semicolons": query.count(";"),
        "equals": query.count("="),
        "parentheses": query.count("(") + query.count(")"),
        "commas": query.count(","),
        "slashes": query.count("/"),

        # SQL operators
        "or_count": len(re.findall(r"\bor\b", q)),
        "and_count": len(re.findall(r"\band\b", q)),
        "between_count": len(re.findall(r"\bbetween\b", q)),

        # SQL keywords
        "select_count": len(re.findall(r"\bselect\b", q)),
        "from_count": len(re.findall(r"\bfrom\b", q)),
        "where_count": len(re.findall(r"\bwhere\b", q)),
        "union_count": len(re.findall(r"\bunion\b", q)),
        "insert_count": len(re.findall(r"\binsert\b", q)),
        "update_count": len(re.findall(r"\bupdate\b", q)),
        "delete_count": len(re.findall(r"\bdelete\b", q)),
        "drop_count": len(re.findall(r"\bdrop\b", q)),
        "truncate_count": len(re.findall(r"\btruncate\b", q)),
        "create_count": len(re.findall(r"\bcreate\b", q)),
        "alter_count": len(re.findall(r"\balter\b", q)),

        # Common injection indicators
        "comment_count": len(re.findall(r"--|/\*|\*/|#", query)),
        "hex_count": len(re.findall(r"0x[0-9a-f]+", q)),
        "sleep_count": len(re.findall(r"\bsleep\b", q)),
        "benchmark_count": len(re.findall(r"\bbenchmark\b", q)),
        "xp_cmdshell_count": len(re.findall(r"xp_cmdshell", q)),

        "statement_count": len([
            x for x in query.split(";")
            if x.strip()
        ]),

        "semicolon_after_quote": int(
            bool(re.search(r"['\"].*;", query, re.DOTALL))
        ),

        "comment_after_semicolon": int(
            bool(re.search(r";.*(--|#|/\*)", query, re.DOTALL))
        ),

        "quote_before_comment": int(
            bool(re.search(r"['\"].*(--|#|/\*)", query, re.DOTALL))
        ),

        # Boolean patterns
        "tautology_count": len(
            re.findall(
                r"\b\d+\s*=\s*\d+\b",
                q
            )
        ),
    }

    return list(features.values())

In [30]:
normal = "SELECT name FROM users WHERE id = 10"

attack = "' OR 1=1 --"

print(extract_sql_features(normal))
print(extract_sql_features(attack))

[36, 8, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[11, 4, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1]


In [31]:
X_train_sql = np.array([
    extract_sql_features(q)
    for q in X_train
])

X_test_sql = np.array([
    extract_sql_features(q)
    for q in X_test
])

print(X_train_sql.shape)
print(X_test_sql.shape)

(118660, 34)
(29666, 34)


In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_sql_scaled = scaler.fit_transform(X_train_sql)
X_test_sql_scaled = scaler.transform(X_test_sql)

In [33]:
from scipy.sparse import csr_matrix, hstack

X_train_final = hstack([
    X_train_combined,
    csr_matrix(X_train_sql_scaled)
]).tocsr()

X_test_final = hstack([
    X_test_combined,
    csr_matrix(X_test_sql_scaled)
]).tocsr()

print("Final training shape:", X_train_final.shape)
print("Final testing shape:", X_test_final.shape)

Final training shape: (118660, 150034)
Final testing shape: (29666, 150034)


In [34]:
from sklearn.linear_model import LogisticRegression

final_model = LogisticRegression(
    max_iter=1500,
    C=2.0,
    random_state=42
)

final_model.fit(X_train_final, y_train)

,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",2.0
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1500
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

In [35]:
y_pred_final = final_model.predict(X_test_final)
y_prob_final = final_model.predict_proba(X_test_final)[:, 1]

In [36]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_test, y_pred_final))
print("Precision:", precision_score(y_test, y_pred_final))
print("Recall   :", recall_score(y_test, y_pred_final))
print("F1 Score :", f1_score(y_test, y_pred_final))

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred_final,
    target_names=["Normal SQL", "SQL Injection"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_final))

Accuracy : 0.9934605272028585
Precision: 0.9970866243687686
Recall   : 0.9904180064308682
F1 Score : 0.9937411278874694

Classification Report:
               precision    recall  f1-score   support

   Normal SQL       0.99      1.00      0.99     14116
SQL Injection       1.00      0.99      0.99     15550

     accuracy                           0.99     29666
    macro avg       0.99      0.99      0.99     29666
 weighted avg       0.99      0.99      0.99     29666


Confusion Matrix:
[[14071    45]
 [  149 15401]]


In [37]:
def predict_query(query):
    char_features = char_vectorizer.transform([query])
    word_features = word_vectorizer.transform([query])

    tfidf_features = hstack([
        char_features,
        word_features
    ]).tocsr()

    sql_features = np.array([
        extract_sql_features(query)
    ])

    sql_features = scaler.transform(sql_features)

    final_features = hstack([
        tfidf_features,
        csr_matrix(sql_features)
    ]).tocsr()

    probability = final_model.predict_proba(
        final_features
    )[0, 1]

    prediction = int(probability >= 0.5)

    return {
        "prediction": (
            "SQL Injection"
            if prediction == 1
            else "Safe"
        ),
        "probability": float(probability)
    }

In [56]:
def predict_query_nofe(query):
    char_features = char_vectorizer.transform([query])
    word_features = word_vectorizer.transform([query])

    tfidf_features = hstack([
        char_features,
        word_features
    ]).tocsr()

    probability = combined_model.predict_proba(
        tfidf_features
    )[0, 1]

    prediction = int(probability >= 0.5)

    return {
        "prediction": (
            "SQL Injection"
            if prediction == 1
            else "Safe"
        ),
        "probability": float(probability)
    }

In [46]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.08,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train_final, y_train)

y_pred_xgb_final = xgb_model.predict(X_test_final)

In [53]:
print("Accuracy :", accuracy_score(y_test, y_pred_xgb_final))
print("Precision:", precision_score(y_test, y_pred_xgb_final))
print("Recall   :", recall_score(y_test, y_pred_xgb_final))
print("F1 Score :", f1_score(y_test, y_pred_xgb_final))
print(classification_report(
    y_test,
    y_pred_xgb_final,
    target_names=["Normal SQL", "SQL Injection"]
))

print(confusion_matrix(y_test, y_pred_xgb_final))

Accuracy : 0.9972021843187487
Precision: 0.9985816517310296
Recall   : 0.9960771704180065
F1 Score : 0.9973278387688741
               precision    recall  f1-score   support

   Normal SQL       1.00      1.00      1.00     14116
SQL Injection       1.00      1.00      1.00     15550

     accuracy                           1.00     29666
    macro avg       1.00      1.00      1.00     29666
 weighted avg       1.00      1.00      1.00     29666

[[14094    22]
 [   61 15489]]


In [48]:
print(
    predict_query(
        "SELECT name FROM users WHERE id = 10"
    )
)

{'prediction': 'Safe', 'probability': 0.14851304626919307}


In [67]:
import joblib

# Save feature-engineered components
joblib.dump(char_vectorizer, "models pkl files/char_vectorizer_fe.pkl")
joblib.dump(word_vectorizer, "models pkl files/word_vectorizer_fe.pkl")
joblib.dump(scaler, "models pkl files/sql_feature_scaler.pkl")
joblib.dump(final_model, "models pkl files/final_model_fe.pkl")
joblib.dump(svd, "models pkl files/svd.pkl")
joblib.dump(xgb_model, "models pkl files/xgb_model.pkl")
joblib.dump(combined_model, "models pkl files/combined_model.pkl")
print("XGBoost components saved.")
print("Feature-engineered models saved.")

XGBoost components saved.
Feature-engineered models saved.


In [50]:
safe_tests = [
    "SELECT * FROM employees",

    "SELECT employee_id, name FROM employees WHERE employee_id = 101",

    "SELECT * FROM employees WHERE department = 'IT'",

    "SELECT * FROM employees WHERE salary > 50000",

    "SELECT * FROM employees WHERE salary >= 50000 AND department = 'IT'",

    "SELECT * FROM employees WHERE department = 'IT' OR department = 'HR'",

    "SELECT * FROM employees WHERE employee_id BETWEEN 100 AND 110",

    "SELECT * FROM employees WHERE name = 'John Smith'",

    "SELECT COUNT(*) FROM employees",

    "SELECT department, AVG(salary) FROM employees GROUP BY department",

    "SELECT * FROM employees ORDER BY name ASC",

    "SELECT employee_id, name FROM employees WHERE employee_id IN (101, 102, 103)",

    "SELECT * FROM employees WHERE name LIKE 'John%'",

    "SELECT e.name, d.department_name FROM employees e JOIN departments d ON e.department_id = d.department_id",

    "SELECT * FROM employees WHERE salary > 50000 AND (department = 'IT' OR department = 'HR')"
]

In [58]:
for query in safe_tests:
    result = predict_query_nofe(query)
    print(f"Query: {query}")
    print(f"Prediction: {result['prediction']}, Probability: {result['probability']:.4f}\n")

Query: SELECT * FROM employees
Prediction: Safe, Probability: 0.0000

Query: SELECT employee_id, name FROM employees WHERE employee_id = 101
Prediction: Safe, Probability: 0.1132

Query: SELECT * FROM employees WHERE department = 'IT'
Prediction: Safe, Probability: 0.0009

Query: SELECT * FROM employees WHERE salary > 50000
Prediction: Safe, Probability: 0.0015

Query: SELECT * FROM employees WHERE salary >= 50000 AND department = 'IT'
Prediction: Safe, Probability: 0.0136

Query: SELECT * FROM employees WHERE department = 'IT' OR department = 'HR'
Prediction: Safe, Probability: 0.0126

Query: SELECT * FROM employees WHERE employee_id BETWEEN 100 AND 110
Prediction: Safe, Probability: 0.0072

Query: SELECT * FROM employees WHERE name = 'John Smith'
Prediction: Safe, Probability: 0.0012

Query: SELECT COUNT(*) FROM employees
Prediction: Safe, Probability: 0.0034

Query: SELECT department, AVG(salary) FROM employees GROUP BY department
Prediction: Safe, Probability: 0.0011

Query: SELECT

In [51]:
for query in safe_tests:
    result = predict_query(query)
    print(f"Query: {query}")
    print(f"Prediction: {result['prediction']}, Probability: {result['probability']:.4f}\n")

Query: SELECT * FROM employees
Prediction: Safe, Probability: 0.0000

Query: SELECT employee_id, name FROM employees WHERE employee_id = 101
Prediction: Safe, Probability: 0.0432

Query: SELECT * FROM employees WHERE department = 'IT'
Prediction: Safe, Probability: 0.0004

Query: SELECT * FROM employees WHERE salary > 50000
Prediction: Safe, Probability: 0.0002

Query: SELECT * FROM employees WHERE salary >= 50000 AND department = 'IT'
Prediction: Safe, Probability: 0.0020

Query: SELECT * FROM employees WHERE department = 'IT' OR department = 'HR'
Prediction: Safe, Probability: 0.0121

Query: SELECT * FROM employees WHERE employee_id BETWEEN 100 AND 110
Prediction: Safe, Probability: 0.0023

Query: SELECT * FROM employees WHERE name = 'John Smith'
Prediction: Safe, Probability: 0.0010

Query: SELECT COUNT(*) FROM employees
Prediction: Safe, Probability: 0.0056

Query: SELECT department, AVG(salary) FROM employees GROUP BY department
Prediction: Safe, Probability: 0.0027

Query: SELECT

In [62]:
mixed_tests = [
    # 1
    "SELECT * FROM employees WHERE employee_id = 101",

    # 2
    "' OR '1'='1",

    # 3
    "SELECT * FROM employees WHERE department = 'IT' OR department = 'HR'",

    # 4
    "101' OR '1'='1' --",

    # 5
    "SELECT name FROM employees WHERE salary > 60000 AND department = 'IT'",

    # 6
    "' AND 1=2 --",

    # 7
    "SELECT * FROM employees WHERE name = 'John' AND employee_id = 101",

    # 8
    "101 OR 1=1",

    # 9
    "SELECT COUNT(*) FROM employees",

    # 10
    "' UNION SELECT NULL --",

    # 11
    "SELECT * FROM employees WHERE employee_id IN (101, 102, 103)",

    # 12
    "101' --",

    # 13
    "SELECT department, AVG(salary) FROM employees GROUP BY department",

    # 14
    "' OR EXISTS (SELECT 1) --",

    # 15
    "SELECT * FROM employees WHERE salary BETWEEN 50000 AND 80000",

    # 16
    "admin' AND '1'='2",

    # 17
    "SELECT * FROM employees WHERE name LIKE 'John%'",

    # 18
    "' OR (1=1) --",

    # 19
    "SELECT e.name FROM employees e WHERE e.department = 'IT'",

    # 20
    "' UNION SELECT username, password FROM users --",

    # 21
    "SELECT * FROM employees WHERE department <> 'HR'",

    # 22
    "101 AND 1=1",

    # 23
    "SELECT * FROM employees WHERE (department = 'IT' OR department = 'HR') AND salary > 50000",

    # 24
    "' OR CASE WHEN 1=1 THEN 1 ELSE 0 END=1 --",

    # 25
    "SELECT employee_id, name FROM employees ORDER BY name ASC",

    # 26
    "' OR 'a'='a' --",

    # 27
    "SELECT * FROM employees WHERE employee_id = 101 AND name = 'Alice'",

    # 28
    "' OR SLEEP(5) --",

    # 29
    "SELECT * FROM employees WHERE name = 'O''Brien'",

    # 30
    "' UNION SELECT NULL WHERE 1=1 --",
]

In [63]:
for query in mixed_tests:
    result = predict_query_nofe(query)

    print(f"Query: {query}")
    print(
        f"Prediction: {result['prediction']}, "
        f"Probability: {result['probability']:.4f}"
    )
    print()

Query: SELECT * FROM employees WHERE employee_id = 101
Prediction: Safe, Probability: 0.0074

Query: ' OR '1'='1
Prediction: SQL Injection, Probability: 1.0000

Query: SELECT * FROM employees WHERE department = 'IT' OR department = 'HR'
Prediction: Safe, Probability: 0.0126

Query: 101' OR '1'='1' --
Prediction: SQL Injection, Probability: 1.0000

Query: SELECT name FROM employees WHERE salary > 60000 AND department = 'IT'
Prediction: Safe, Probability: 0.1081

Query: ' AND 1=2 --
Prediction: SQL Injection, Probability: 0.9997

Query: SELECT * FROM employees WHERE name = 'John' AND employee_id = 101
Prediction: Safe, Probability: 0.0415

Query: 101 OR 1=1
Prediction: SQL Injection, Probability: 0.9822

Query: SELECT COUNT(*) FROM employees
Prediction: Safe, Probability: 0.0034

Query: ' UNION SELECT NULL --
Prediction: SQL Injection, Probability: 0.9998

Query: SELECT * FROM employees WHERE employee_id IN (101, 102, 103)
Prediction: Safe, Probability: 0.0026

Query: 101' --
Prediction:

In [64]:
expected = [
    0,  # 1  Safe
    1,  # 2  SQLi
    0,  # 3  Safe
    1,  # 4  SQLi
    0,  # 5  Safe
    1,  # 6  SQLi
    0,  # 7  Safe
    1,  # 8  SQLi
    0,  # 9  Safe
    1,  # 10 SQLi
    0,  # 11 Safe
    1,  # 12 SQLi
    0,  # 13 Safe
    1,  # 14 SQLi
    0,  # 15 Safe
    1,  # 16 SQLi
    0,  # 17 Safe
    1,  # 18 SQLi
    0,  # 19 Safe
    1,  # 20 SQLi
    0,  # 21 Safe
    1,  # 22 SQLi
    0,  # 23 Safe
    1,  # 24 SQLi
    0,  # 25 Safe
    1,  # 26 SQLi
    0,  # 27 Safe
    1,  # 28 SQLi
    0,  # 29 Safe
    1,  # 30 SQLi
]

In [65]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

predictions = []

for query in mixed_tests:
    result = predict_query_nofe(query)

    predictions.append(
        1 if result["prediction"] == "SQL Injection" else 0
    )

accuracy = accuracy_score(expected, predictions)
precision = precision_score(expected, predictions, zero_division=0)
recall = recall_score(expected, predictions, zero_division=0)
f1 = f1_score(expected, predictions, zero_division=0)

tn, fp, fn, tp = confusion_matrix(
    expected,
    predictions
).ravel()

print("=" * 50)
print("MIXED TEST ANALYSIS")
print("=" * 50)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

print()
print(f"True Negatives : {tn}")
print(f"False Positives: {fp}")
print(f"False Negatives: {fn}")
print(f"True Positives : {tp}")

print()
print("MISCLASSIFICATIONS")
print("=" * 50)

for i, (query, actual, predicted) in enumerate(
    zip(mixed_tests, expected, predictions),
    1
):
    if actual != predicted:
        print(f"{i}. {query}")
        print(f"   Expected : {'SQL Injection' if actual else 'Safe'}")
        print(f"   Predicted: {'SQL Injection' if predicted else 'Safe'}")

MIXED TEST ANALYSIS
Accuracy : 1.0000
Precision: 1.0000
Recall   : 1.0000
F1 Score : 1.0000

True Negatives : 15
False Positives: 0
False Negatives: 0
True Positives : 15

MISCLASSIFICATIONS
